[package]
name = "rl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.6"
rand = "0.8.5"
rand_pcg = "0.3.1"
rand_seeder = "0.2.3"
